-- Live pipeline reliability spine
-- Goal: detect + recover missing/stale live odds snapshots and PBP/live state coverage per started game.

-- 1) Configurable freshness thresholds
CREATE TABLE IF NOT EXISTS public.live_pipeline_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_active BOOLEAN NOT NULL DEFAULT true,
  snapshot_stale_seconds INTEGER NOT NULL DEFAULT 90 CHECK (snapshot_stale_seconds > 0),
  pbp_stale_seconds INTEGER NOT NULL DEFAULT 60 CHECK (pbp_stale_seconds > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_live_pipeline_config_active
  ON public.live_pipeline_config ((is_active))
  WHERE is_active;

INSERT INTO public.live_pipeline_config (is_active, snapshot_stale_seconds, pbp_stale_seconds)
SELECT true, 90, 60
WHERE NOT EXISTS (SELECT 1 FROM public.live_pipeline_config WHERE is_active = true);

-- 2) Structured reliability logs for live ingestion/recovery runs
CREATE TABLE IF NOT EXISTS public.live_pipeline_reliability_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id UUID REFERENCES public.job_runs(id) ON DELETE SET NULL,
  function_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'succeeded', 'failed', 'replayed')),
  trigger_type TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (trigger_type IN ('scheduled', 'watchdog', 'replay', 'manual')),
  scanned_games INTEGER NOT NULL DEFAULT 0,
  started_games INTEGER NOT NULL DEFAULT 0,
  snapshot_writes INTEGER NOT NULL DEFAULT 0,
  live_state_writes INTEGER NOT NULL DEFAULT 0,
  pbp_writes INTEGER NOT NULL DEFAULT 0,
  missing_games INTEGER NOT NULL DEFAULT 0,
  stale_games INTEGER NOT NULL DEFAULT 0,
  retries_attempted INTEGER NOT NULL DEFAULT 0,
  retries_recovered INTEGER NOT NULL DEFAULT 0,
  provider_failures INTEGER NOT NULL DEFAULT 0,
  degraded_snapshot_writes INTEGER NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_live_pipeline_reliability_logs_created_at
  ON public.live_pipeline_reliability_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_live_pipeline_reliability_logs_function
  ON public.live_pipeline_reliability_logs (function_name, created_at DESC);

ALTER TABLE public.live_pipeline_reliability_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all" ON public.live_pipeline_reliability_logs;
CREATE POLICY "service_role_all"
  ON public.live_pipeline_reliability_logs
  FOR ALL
  USING ((SELECT auth.role()) = 'service_role');

DROP POLICY IF EXISTS "public_read" ON public.live_pipeline_reliability_logs;
CREATE POLICY "public_read"
  ON public.live_pipeline_reliability_logs
  FOR SELECT
  USING (true);

-- 3) Performance indexes for live coverage audits
CREATE INDEX IF NOT EXISTS idx_live_odds_snapshots_match_captured
  ON public.live_odds_snapshots (match_id, captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_live_game_state_id_updated
  ON public.live_game_state (id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_game_events_match_play_created
  ON public.game_events (match_id, event_type, created_at DESC)
  WHERE event_type = 'play';

CREATE INDEX IF NOT EXISTS idx_matches_live_coverage_window
  ON public.matches (league_id, sport, start_time DESC);

-- 4) Canonical game-level coverage view
DROP VIEW IF EXISTS public.vw_live_pipeline_coverage CASCADE;
CREATE OR REPLACE VIEW public.vw_live_pipeline_coverage AS
WITH cfg AS (
  SELECT
    COALESCE(
      (SELECT snapshot_stale_seconds
       FROM public.live_pipeline_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      90
    ) AS snapshot_stale_seconds,
    COALESCE(
      (SELECT pbp_stale_seconds
       FROM public.live_pipeline_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      60
    ) AS pbp_stale_seconds
),
base_games AS (
  SELECT
    m.id AS match_id,
    COALESCE(m.league_id, 'unknown') AS league_id,
    COALESCE(m.sport, 'unknown') AS sport,
    m.start_time,
    COALESCE(m.status, 'STATUS_SCHEDULED') AS raw_status,
    CASE
      WHEN upper(COALESCE(m.status, '')) LIKE '%FINAL%'
        OR upper(COALESCE(m.status, '')) LIKE '%POST%'
        THEN 'FINAL'
      WHEN upper(COALESCE(m.status, '')) LIKE '%IN_PROGRESS%'
        OR upper(COALESCE(m.status, '')) LIKE '%LIVE%'
        OR upper(COALESCE(m.status, '')) LIKE '%HALF%'
        THEN 'IN_PROGRESS'
      ELSE 'SCHEDULED'
    END AS game_phase
  FROM public.matches m
  WHERE m.start_time >= now() - interval '7 days'
),
snapshot_stats AS (
  SELECT
    los.match_id,
    MIN(los.captured_at) AS first_snapshot_at,
    MAX(los.captured_at) AS latest_snapshot_at,
    COUNT(*)::INTEGER AS snapshot_count
  FROM public.live_odds_snapshots los
  WHERE los.captured_at >= now() - interval '7 days'
  GROUP BY los.match_id
),
state_stats AS (
  SELECT
    lgs.id AS match_id,
    MAX(lgs.updated_at) AS latest_live_state_at,
    MAX(
      CASE
        WHEN lgs.recent_plays IS NULL THEN 0
        WHEN jsonb_typeof(lgs.recent_plays) = 'array' AND jsonb_array_length(lgs.recent_plays) = 0 THEN 0
        ELSE 1
      END
    ) = 1 AS has_recent_plays_state
  FROM public.live_game_state lgs
  GROUP BY lgs.id
),
pbp_stats AS (
  SELECT
    ge.match_id,
    MAX(ge.created_at) AS latest_pbp_event_at,
    COUNT(*)::INTEGER AS pbp_count
  FROM public.game_events ge
  WHERE ge.event_type = 'play'
    AND ge.created_at >= now() - interval '7 days'
  GROUP BY ge.match_id
),
joined AS (
  SELECT
    g.match_id,
    g.league_id,
    g.sport,
    g.start_time,
    g.raw_status,
    g.game_phase,
    (g.game_phase <> 'SCHEDULED' OR g.start_time <= now() - interval '5 minutes') AS started,
    (g.game_phase = 'FINAL') AS final,
    COALESCE(s.snapshot_count, 0) > 0 AS has_live_odds_snapshot,
    s.first_snapshot_at,
    s.latest_snapshot_at,
    COALESCE(s.snapshot_count, 0) AS snapshot_count,
    (st.latest_live_state_at IS NOT NULL) AS has_live_state,
    st.latest_live_state_at,
    (COALESCE(p.pbp_count, 0) > 0 OR COALESCE(st.has_recent_plays_state, false)) AS has_pbp,
    CASE
      WHEN COALESCE(p.pbp_count, 0) > 0 AND st.has_recent_plays_state THEN GREATEST(p.latest_pbp_event_at, st.latest_live_state_at)
      WHEN COALESCE(p.pbp_count, 0) > 0 THEN p.latest_pbp_event_at
      WHEN st.has_recent_plays_state THEN st.latest_live_state_at
      ELSE NULL
    END AS latest_pbp_at,
    cfg.snapshot_stale_seconds,
    cfg.pbp_stale_seconds
  FROM base_games g
  LEFT JOIN snapshot_stats s ON s.match_id = g.match_id
  LEFT JOIN state_stats st ON st.match_id = g.match_id
  LEFT JOIN pbp_stats p ON p.match_id = g.match_id
  CROSS JOIN cfg
)
SELECT
  j.match_id,
  j.league_id,
  j.sport,
  j.start_time,
  j.raw_status,
  j.game_phase,
  j.started,
  j.final,
  j.has_live_odds_snapshot,
  j.first_snapshot_at,
  j.latest_snapshot_at,
  j.snapshot_count,
  j.has_live_state,
  j.latest_live_state_at,
  j.has_pbp,
  j.latest_pbp_at,
  CASE
    WHEN j.game_phase = 'IN_PROGRESS' AND j.latest_snapshot_at IS NOT NULL
      THEN GREATEST(0, EXTRACT(EPOCH FROM (now() - j.latest_snapshot_at))::INTEGER)
    ELSE NULL
  END AS stale_seconds_snapshot,
  CASE
    WHEN j.game_phase = 'IN_PROGRESS' AND (j.has_live_state OR j.has_pbp) AND COALESCE(j.latest_pbp_at, j.latest_live_state_at) IS NOT NULL
      THEN GREATEST(0, EXTRACT(EPOCH FROM (now() - COALESCE(j.latest_pbp_at, j.latest_live_state_at)))::INTEGER)
    ELSE NULL
  END AS stale_seconds_pbp,
  CASE
    WHEN j.started AND NOT j.has_live_odds_snapshot AND NOT j.has_live_state AND NOT j.has_pbp THEN 'MISSING_BOTH'
    WHEN j.started AND NOT j.has_live_odds_snapshot THEN 'MISSING_SNAPSHOT'
    WHEN j.started AND NOT (j.has_live_state OR j.has_pbp) THEN 'MISSING_PBP'
    WHEN j.game_phase = 'IN_PROGRESS'
      AND j.latest_snapshot_at IS NOT NULL
      AND EXTRACT(EPOCH FROM (now() - j.latest_snapshot_at))::INTEGER > j.snapshot_stale_seconds
      THEN 'STALE_SNAPSHOT'
    WHEN j.game_phase = 'IN_PROGRESS'
      AND COALESCE(j.latest_pbp_at, j.latest_live_state_at) IS NOT NULL
      AND EXTRACT(EPOCH FROM (now() - COALESCE(j.latest_pbp_at, j.latest_live_state_at)))::INTEGER > j.pbp_stale_seconds
      THEN 'STALE_PBP'
    ELSE 'OK'
  END AS coverage_status
FROM joined j;

GRANT SELECT ON public.vw_live_pipeline_coverage TO anon, authenticated, service_role;

-- 5) Sport/league summary materialized view
DROP MATERIALIZED VIEW IF EXISTS public.mv_live_pipeline_coverage_summary CASCADE;
CREATE MATERIALIZED VIEW public.mv_live_pipeline_coverage_summary AS
SELECT
  sport,
  league_id,
  COUNT(*)::INTEGER AS total_games,
  COUNT(*) FILTER (WHERE started)::INTEGER AS started_games,
  COUNT(*) FILTER (WHERE game_phase = 'IN_PROGRESS')::INTEGER AS in_progress_games,
  COUNT(*) FILTER (WHERE final)::INTEGER AS final_games,
  COUNT(*) FILTER (WHERE started AND has_live_odds_snapshot)::INTEGER AS started_with_snapshot,
  COUNT(*) FILTER (WHERE started AND (has_live_state OR has_pbp))::INTEGER AS started_with_pbp_or_state,
  COUNT(*) FILTER (WHERE started AND has_pbp)::INTEGER AS started_with_pbp,
  COUNT(*) FILTER (WHERE coverage_status = 'MISSING_SNAPSHOT')::INTEGER AS missing_snapshot_games,
  COUNT(*) FILTER (WHERE coverage_status = 'MISSING_PBP')::INTEGER AS missing_pbp_games,
  COUNT(*) FILTER (WHERE coverage_status = 'MISSING_BOTH')::INTEGER AS missing_both_games,
  COUNT(*) FILTER (WHERE coverage_status = 'STALE_SNAPSHOT')::INTEGER AS stale_snapshot_games,
  COUNT(*) FILTER (WHERE coverage_status = 'STALE_PBP')::INTEGER AS stale_pbp_games,
  COUNT(*) FILTER (WHERE coverage_status = 'OK')::INTEGER AS ok_games,
  CASE
    WHEN COUNT(*) FILTER (WHERE started) > 0
      THEN ROUND(
        100.0 * COUNT(*) FILTER (WHERE started AND has_live_odds_snapshot)
        / COUNT(*) FILTER (WHERE started),
        2
      )
    ELSE 100.0
  END AS snapshot_coverage_pct,
  CASE
    WHEN COUNT(*) FILTER (WHERE started) > 0
      THEN ROUND(
        100.0 * COUNT(*) FILTER (WHERE started AND (has_live_state OR has_pbp))
        / COUNT(*) FILTER (WHERE started),
        2
      )
    ELSE 100.0
  END AS pbp_state_coverage_pct,
  now() AS refreshed_at
FROM public.vw_live_pipeline_coverage
GROUP BY sport, league_id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_live_pipeline_coverage_summary_pk
  ON public.mv_live_pipeline_coverage_summary (sport, league_id);

GRANT SELECT ON public.mv_live_pipeline_coverage_summary TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.refresh_mv_live_pipeline_coverage_summary()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW public.mv_live_pipeline_coverage_summary;
END;
$$;

SELECT public.refresh_mv_live_pipeline_coverage_summary();

-- 6) Optional registry entries for control-plane visibility
INSERT INTO public.data_registry (
  object_name,
  physical_table,
  source_system,
  primary_key,
  family,
  naming_tier,
  canonical_name,
  description,
  row_count_snapshot
)
SELECT * FROM (
  VALUES
    (
      'live_pipeline_reliability_logs',
      'public.live_pipeline_reliability_logs',
      'supabase',
      'id',
      'control',
      'JOB',
      'JOB_LIVE_PIPELINE_RELIABILITY',
      'Run-level reliability metrics for ingest-live-games and recovery paths',
      0
    )
) v(object_name, physical_table, source_system, primary_key, family, naming_tier, canonical_name, description, row_count_snapshot)
ON CONFLICT (object_name) DO NOTHING;
