ALTER TABLE llm_model_picks
ADD COLUMN IF NOT EXISTS is_fallback BOOLEAN DEFAULT false;

ALTER TABLE llm_model_picks
ADD COLUMN IF NOT EXISTS fallback_reason TEXT;

ALTER TABLE llm_model_picks
ADD COLUMN IF NOT EXISTS primary_model TEXT;

ALTER TABLE llm_model_picks
ADD COLUMN IF NOT EXISTS extraction_version TEXT DEFAULT 'regex-v1';

CREATE INDEX IF NOT EXISTS idx_llm_model_picks_fallback
  ON llm_model_picks(is_fallback)
  WHERE is_fallback = true;

CREATE INDEX IF NOT EXISTS idx_llm_model_picks_model_extraction
  ON llm_model_picks(model_id, extraction_version);

COMMENT ON COLUMN llm_model_picks.is_fallback IS
  'True if generated by a fallback model after primary failure.';
COMMENT ON COLUMN llm_model_picks.fallback_reason IS
  'Why fallback triggered: quota_exceeded, rate_limited, primary_timeout, primary_error.';
COMMENT ON COLUMN llm_model_picks.primary_model IS
  'Model that would have been used if no fallback. NULL when is_fallback = false.';
COMMENT ON COLUMN llm_model_picks.extraction_version IS
  'Pick extraction logic version (e.g. regex-v1).';
