-- Live pipeline capability matrix + current SLO surface.
-- Purpose: make per-league expectations explicit (including PBP support),
-- then expose league-level SLO breach status in SQL for operational guardrails.

CREATE TABLE IF NOT EXISTS public.live_pipeline_capabilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id TEXT NOT NULL UNIQUE,
  sport TEXT NOT NULL,
  live_odds_supported BOOLEAN NOT NULL DEFAULT true,
  live_state_supported BOOLEAN NOT NULL DEFAULT true,
  pbp_supported BOOLEAN NOT NULL DEFAULT true,
  auto_recovery_enabled BOOLEAN NOT NULL DEFAULT true,
  slo_enforced BOOLEAN NOT NULL DEFAULT true,
  is_active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_live_pipeline_capabilities_active
  ON public.live_pipeline_capabilities (is_active, sport, league_id);

ALTER TABLE public.live_pipeline_capabilities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all" ON public.live_pipeline_capabilities;
CREATE POLICY "service_role_all"
  ON public.live_pipeline_capabilities
  FOR ALL
  USING ((SELECT auth.role()) = 'service_role');

DROP POLICY IF EXISTS "public_read" ON public.live_pipeline_capabilities;
CREATE POLICY "public_read"
  ON public.live_pipeline_capabilities
  FOR SELECT
  USING (true);

INSERT INTO public.live_pipeline_capabilities (
  league_id,
  sport,
  live_odds_supported,
  live_state_supported,
  pbp_supported,
  auto_recovery_enabled,
  slo_enforced,
  is_active,
  notes
)
VALUES
  ('nfl', 'americanfootball', true, true, true, true, true, true, 'default capability seed'),
  ('nba', 'basketball', true, true, true, true, true, true, 'default capability seed'),
  ('wnba', 'basketball', true, true, true, true, true, true, 'default capability seed'),
  ('mlb', 'baseball', true, true, true, true, true, true, 'default capability seed'),
  ('nhl', 'icehockey', true, true, true, true, true, true, 'default capability seed'),
  ('mens-college-basketball', 'basketball', true, true, true, true, true, true, 'default capability seed'),
  ('college-football', 'americanfootball', true, true, true, true, true, true, 'default capability seed'),
  ('epl', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('seriea', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('bundesliga', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('laliga', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('ligue1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('mls', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('mex.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('ucl', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('uel', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('ned.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('por.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('bel.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('tur.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('bra.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('arg.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('sco.1', 'soccer', true, true, true, true, true, true, 'default capability seed'),
  ('atp', 'tennis', true, true, false, true, false, true, 'PBP often unavailable; SLO disabled by default'),
  ('wta', 'tennis', true, true, false, true, false, true, 'PBP often unavailable; SLO disabled by default')
ON CONFLICT (league_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.live_pipeline_slo_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_active BOOLEAN NOT NULL DEFAULT true,
  window_minutes INTEGER NOT NULL DEFAULT 240 CHECK (window_minutes > 0),
  min_snapshot_coverage_pct NUMERIC(5,2) NOT NULL DEFAULT 100 CHECK (min_snapshot_coverage_pct >= 0 AND min_snapshot_coverage_pct <= 100),
  min_state_coverage_pct NUMERIC(5,2) NOT NULL DEFAULT 100 CHECK (min_state_coverage_pct >= 0 AND min_state_coverage_pct <= 100),
  min_pbp_coverage_pct NUMERIC(5,2) NOT NULL DEFAULT 100 CHECK (min_pbp_coverage_pct >= 0 AND min_pbp_coverage_pct <= 100),
  max_missing_games INTEGER NOT NULL DEFAULT 0 CHECK (max_missing_games >= 0),
  max_stale_games INTEGER NOT NULL DEFAULT 0 CHECK (max_stale_games >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_live_pipeline_slo_config_active
  ON public.live_pipeline_slo_config ((is_active))
  WHERE is_active;

ALTER TABLE public.live_pipeline_slo_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all" ON public.live_pipeline_slo_config;
CREATE POLICY "service_role_all"
  ON public.live_pipeline_slo_config
  FOR ALL
  USING ((SELECT auth.role()) = 'service_role');

DROP POLICY IF EXISTS "public_read" ON public.live_pipeline_slo_config;
CREATE POLICY "public_read"
  ON public.live_pipeline_slo_config
  FOR SELECT
  USING (true);

INSERT INTO public.live_pipeline_slo_config (
  is_active,
  window_minutes,
  min_snapshot_coverage_pct,
  min_state_coverage_pct,
  min_pbp_coverage_pct,
  max_missing_games,
  max_stale_games
)
SELECT true, 240, 100, 100, 100, 0, 0
WHERE NOT EXISTS (
  SELECT 1
  FROM public.live_pipeline_slo_config
  WHERE is_active = true
);

DROP VIEW IF EXISTS public.vw_live_pipeline_slo_current;
CREATE OR REPLACE VIEW public.vw_live_pipeline_slo_current AS
WITH cfg AS (
  SELECT
    COALESCE(
      (SELECT window_minutes
       FROM public.live_pipeline_slo_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      240
    )::INTEGER AS window_minutes,
    COALESCE(
      (SELECT min_snapshot_coverage_pct
       FROM public.live_pipeline_slo_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      100
    )::NUMERIC AS min_snapshot_coverage_pct,
    COALESCE(
      (SELECT min_state_coverage_pct
       FROM public.live_pipeline_slo_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      100
    )::NUMERIC AS min_state_coverage_pct,
    COALESCE(
      (SELECT min_pbp_coverage_pct
       FROM public.live_pipeline_slo_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      100
    )::NUMERIC AS min_pbp_coverage_pct,
    COALESCE(
      (SELECT max_missing_games
       FROM public.live_pipeline_slo_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      0
    )::INTEGER AS max_missing_games,
    COALESCE(
      (SELECT max_stale_games
       FROM public.live_pipeline_slo_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      0
    )::INTEGER AS max_stale_games
),
freshness AS (
  SELECT
    COALESCE(
      (SELECT snapshot_stale_seconds
       FROM public.live_pipeline_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      90
    )::INTEGER AS snapshot_stale_seconds,
    COALESCE(
      (SELECT pbp_stale_seconds
       FROM public.live_pipeline_config
       WHERE is_active = true
       ORDER BY updated_at DESC, id DESC
       LIMIT 1),
      60
    )::INTEGER AS pbp_stale_seconds
),
caps AS (
  SELECT
    c.league_id,
    c.sport,
    c.live_odds_supported,
    c.live_state_supported,
    c.pbp_supported,
    c.auto_recovery_enabled,
    c.slo_enforced
  FROM public.live_pipeline_capabilities c
  WHERE c.is_active = true
),
windowed AS (
  SELECT
    c.league_id,
    c.sport,
    c.live_odds_supported,
    c.live_state_supported,
    c.pbp_supported,
    c.auto_recovery_enabled,
    c.slo_enforced,
    v.match_id,
    v.game_phase,
    v.started,
    v.has_live_odds_snapshot,
    v.has_live_state,
    v.has_pbp,
    v.stale_seconds_snapshot,
    v.stale_seconds_pbp
  FROM caps c
  CROSS JOIN cfg
  LEFT JOIN public.vw_live_pipeline_coverage v
    ON v.league_id = c.league_id
   AND v.sport = c.sport
   AND v.started = true
   AND v.start_time >= now() - make_interval(mins => cfg.window_minutes)
),
agg AS (
  SELECT
    w.sport,
    w.league_id,
    BOOL_OR(w.live_odds_supported) AS live_odds_supported,
    BOOL_OR(w.live_state_supported) AS live_state_supported,
    BOOL_OR(w.pbp_supported) AS pbp_supported,
    BOOL_OR(w.auto_recovery_enabled) AS auto_recovery_enabled,
    BOOL_OR(w.slo_enforced) AS slo_enforced,
    COUNT(w.match_id)::INTEGER AS started_games,
    COUNT(w.match_id) FILTER (WHERE w.live_odds_supported)::INTEGER AS required_snapshot_games,
    COUNT(w.match_id) FILTER (WHERE w.live_odds_supported AND w.has_live_odds_snapshot)::INTEGER AS covered_snapshot_games,
    COUNT(w.match_id) FILTER (WHERE w.live_state_supported)::INTEGER AS required_state_games,
    COUNT(w.match_id) FILTER (WHERE w.live_state_supported AND w.has_live_state)::INTEGER AS covered_state_games,
    COUNT(w.match_id) FILTER (WHERE w.pbp_supported)::INTEGER AS required_pbp_games,
    COUNT(w.match_id) FILTER (WHERE w.pbp_supported AND w.has_pbp)::INTEGER AS covered_pbp_games,
    COUNT(w.match_id) FILTER (
      WHERE (w.live_odds_supported AND NOT COALESCE(w.has_live_odds_snapshot, false))
         OR (w.live_state_supported AND NOT COALESCE(w.has_live_state, false))
         OR (w.pbp_supported AND NOT COALESCE(w.has_pbp, false))
    )::INTEGER AS missing_required_games,
    COUNT(w.match_id) FILTER (
      WHERE w.game_phase = 'IN_PROGRESS'
        AND (
          (w.live_odds_supported AND COALESCE(w.stale_seconds_snapshot, 0) > f.snapshot_stale_seconds)
          OR (w.pbp_supported AND COALESCE(w.stale_seconds_pbp, 0) > f.pbp_stale_seconds)
        )
    )::INTEGER AS stale_required_games
  FROM windowed w
  CROSS JOIN freshness f
  GROUP BY w.sport, w.league_id
),
final AS (
  SELECT
    a.*,
    CASE
      WHEN a.required_snapshot_games > 0
        THEN ROUND((100.0 * a.covered_snapshot_games::NUMERIC / a.required_snapshot_games::NUMERIC), 2)
      ELSE 100.0
    END AS snapshot_coverage_pct,
    CASE
      WHEN a.required_state_games > 0
        THEN ROUND((100.0 * a.covered_state_games::NUMERIC / a.required_state_games::NUMERIC), 2)
      ELSE 100.0
    END AS state_coverage_pct,
    CASE
      WHEN a.required_pbp_games > 0
        THEN ROUND((100.0 * a.covered_pbp_games::NUMERIC / a.required_pbp_games::NUMERIC), 2)
      ELSE 100.0
    END AS pbp_coverage_pct
  FROM agg a
)
SELECT
  f.sport,
  f.league_id,
  cfg.window_minutes,
  f.live_odds_supported,
  f.live_state_supported,
  f.pbp_supported,
  f.auto_recovery_enabled,
  f.slo_enforced,
  f.started_games,
  f.required_snapshot_games,
  f.covered_snapshot_games,
  f.required_state_games,
  f.covered_state_games,
  f.required_pbp_games,
  f.covered_pbp_games,
  f.missing_required_games,
  f.stale_required_games,
  f.snapshot_coverage_pct,
  f.state_coverage_pct,
  f.pbp_coverage_pct,
  cfg.min_snapshot_coverage_pct,
  cfg.min_state_coverage_pct,
  cfg.min_pbp_coverage_pct,
  cfg.max_missing_games,
  cfg.max_stale_games,
  ARRAY_REMOVE(
    ARRAY[
      CASE WHEN f.snapshot_coverage_pct < cfg.min_snapshot_coverage_pct THEN 'SNAPSHOT_COVERAGE' END,
      CASE WHEN f.state_coverage_pct < cfg.min_state_coverage_pct THEN 'STATE_COVERAGE' END,
      CASE WHEN f.pbp_coverage_pct < cfg.min_pbp_coverage_pct THEN 'PBP_COVERAGE' END,
      CASE WHEN f.missing_required_games > cfg.max_missing_games THEN 'MISSING_REQUIRED' END,
      CASE WHEN f.stale_required_games > cfg.max_stale_games THEN 'STALE_REQUIRED' END
    ],
    NULL
  )::TEXT[] AS breach_reasons,
  (
    f.slo_enforced
    AND (
      f.snapshot_coverage_pct < cfg.min_snapshot_coverage_pct
      OR f.state_coverage_pct < cfg.min_state_coverage_pct
      OR f.pbp_coverage_pct < cfg.min_pbp_coverage_pct
      OR f.missing_required_games > cfg.max_missing_games
      OR f.stale_required_games > cfg.max_stale_games
    )
  ) AS slo_breach
FROM final f
CROSS JOIN cfg;

GRANT SELECT ON public.live_pipeline_capabilities TO anon, authenticated, service_role;
GRANT SELECT ON public.live_pipeline_slo_config TO anon, authenticated, service_role;
GRANT SELECT ON public.vw_live_pipeline_slo_current TO anon, authenticated, service_role;
