ALTER TABLE ai_chat_picks
ADD COLUMN IF NOT EXISTS model_id TEXT;

ALTER TABLE ai_chat_picks
ADD COLUMN IF NOT EXISTS is_fallback BOOLEAN DEFAULT false;

ALTER TABLE ai_chat_picks
ADD COLUMN IF NOT EXISTS fallback_reason TEXT;

ALTER TABLE ai_chat_picks
ADD COLUMN IF NOT EXISTS primary_model TEXT;

CREATE INDEX IF NOT EXISTS idx_ai_chat_picks_model_id
  ON ai_chat_picks(model_id);

CREATE INDEX IF NOT EXISTS idx_ai_chat_picks_fallback
  ON ai_chat_picks(is_fallback)
  WHERE is_fallback = true;

COMMENT ON COLUMN ai_chat_picks.model_id IS
  'AI model that generated this pick. NULL for pre-provenance rows.';
COMMENT ON COLUMN ai_chat_picks.is_fallback IS
  'True if generated by a fallback model after primary failure.';
COMMENT ON COLUMN ai_chat_picks.fallback_reason IS
  'Why fallback triggered: quota_exceeded, rate_limited, primary_timeout, primary_error.';
COMMENT ON COLUMN ai_chat_picks.primary_model IS
  'Model that would have been used if no fallback. NULL when is_fallback = false.';
