ALTER TABLE live_game_state 
ADD COLUMN IF NOT EXISTS last_play JSONB,
ADD COLUMN IF NOT EXISTS situation JSONB,
ADD COLUMN IF NOT EXISTS current_drive JSONB,
ADD COLUMN IF NOT EXISTS recent_plays JSONB,
ADD COLUMN IF NOT EXISTS stats JSONB,
ADD COLUMN IF NOT EXISTS player_stats JSONB,
ADD COLUMN IF NOT EXISTS leaders JSONB,
ADD COLUMN IF NOT EXISTS momentum JSONB,
ADD COLUMN IF NOT EXISTS advanced_metrics JSONB,
ADD COLUMN IF NOT EXISTS match_context JSONB,
ADD COLUMN IF NOT EXISTS predictor JSONB;;
